// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMV3762RYA07_qi2QrWGx2m1Dtd3nNINA',
    appId: '1:931491036586:web:ba9fda1a5c57f98026bfd3',
    messagingSenderId: '931491036586',
    projectId: 'labtestmobileapp-95a9f',
    authDomain: 'labtestmobileapp-95a9f.firebaseapp.com',
    storageBucket: 'labtestmobileapp-95a9f.firebasestorage.app',
    measurementId: 'G-3QP28LB81R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCKCwul2vauUheHxPr5iVmn00_mTztgRM',
    appId: '1:931491036586:android:0621c927befb9ea526bfd3',
    messagingSenderId: '931491036586',
    projectId: 'labtestmobileapp-95a9f',
    storageBucket: 'labtestmobileapp-95a9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwsjq27kE6F_CYsDtqiAHKEnx7GVepJJM',
    appId: '1:931491036586:ios:1700be011d3c96d326bfd3',
    messagingSenderId: '931491036586',
    projectId: 'labtestmobileapp-95a9f',
    storageBucket: 'labtestmobileapp-95a9f.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwsjq27kE6F_CYsDtqiAHKEnx7GVepJJM',
    appId: '1:931491036586:ios:1700be011d3c96d326bfd3',
    messagingSenderId: '931491036586',
    projectId: 'labtestmobileapp-95a9f',
    storageBucket: 'labtestmobileapp-95a9f.firebasestorage.app',
    iosBundleId: 'com.example.labtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMV3762RYA07_qi2QrWGx2m1Dtd3nNINA',
    appId: '1:931491036586:web:b87711f7a9e9d54926bfd3',
    messagingSenderId: '931491036586',
    projectId: 'labtestmobileapp-95a9f',
    authDomain: 'labtestmobileapp-95a9f.firebaseapp.com',
    storageBucket: 'labtestmobileapp-95a9f.firebasestorage.app',
    measurementId: 'G-90GCW3M5MZ',
  );
}
